# Generated by Django 4.2.3 on 2023-07-03 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_conta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='esencial',
            new_name='essencial',
        ),
    ]
